# Generated by Django 6.0.7 on 2026-07-29 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_labels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('show_niimbot_button', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'QR settings',
                'verbose_name_plural': 'QR settings',
            },
        ),
    ]
