# Generated by Django 6.0.7 on 2026-07-29 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_qr', '0002_qrsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrtemplate',
            name='editor_mode',
            field=models.CharField(default='code', max_length=10),
        ),
        migrations.AddField(
            model_name='qrtemplate',
            name='layout',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
