# Generated by Django 6.0.7 on 2026-07-29 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_qr', '0003_qrtemplate_editor_mode_qrtemplate_layout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qrtemplate',
            name='editor_mode',
        ),
        migrations.AddField(
            model_name='qrtemplate',
            name='height_mm',
            field=models.DecimalField(decimal_places=1, default=12, max_digits=6),
        ),
        migrations.AddField(
            model_name='qrtemplate',
            name='width_mm',
            field=models.DecimalField(decimal_places=1, default=40, max_digits=6),
        ),
    ]
