# Generated by Django 6.0.7 on 2026-07-30 05:20

import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0140_imageattachment_image_size'),
        ('netbox_qr', '0004_remove_qrtemplate_editor_mode_qrtemplate_height_mm_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRSizePreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('width_mm', models.DecimalField(decimal_places=1, max_digits=6)),
                ('height_mm', models.DecimalField(decimal_places=1, max_digits=6)),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'QR size preset',
                'verbose_name_plural': 'QR size presets',
                'ordering': ('name',),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
    ]
